# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-16 15:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('short_url_tag', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('original_url', models.CharField(max_length=300)),
                ('custom_tag', models.CharField(blank=True, max_length=250, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('short_url', models.CharField(max_length=200)),
            ],
        ),
    ]
